language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
  script:
    - npm install
    - npm install jest-cli
    - npm test
  env:
    global:
      - CI=true
    after_success:
      - eval "$(ssh-agent -s)" #start the ssh agent
      - chmod 600 .travis/deploy.key # this key should have push access
      - ssh-add .travis/deploy.key
      - ssh-keyscan $PRODUCTION_SERVER >> ~/.ssh/known_hosts
      - git remote add deploy $PRODUCTION_GIT_URL
      - git config --global push.default simple
      - git push deploy master
